### PR TITLE
debezium/dbz#1836: Add SQL Server-specific db name config in Pipelinemapper

### LINKED ISSUE #1828: PipelineMapper Does Not Handle SQL Server-Specific 'database.names' Property
# Bug Report

## Environment:
* `debezium-platform` deployed with the official Helm chart.
* `debezium-operator` version `3.5.0`.
* `nightly` tag for `operator` and `stage` images.

Using the UI, I created the following components:

* Connection to SQL Server 2022 with validation passing in the UI.
* Source referencing the connection.
* Kafka destination.
* Pipeline using those components.

However the pipeline is not working with the following error:

`2026-04-16 13:18:01,958 INFO  [io.deb.emb.asy.AsyncEmbeddedEngine] (pool-8-thread-1) Engine state has changed from 'INITIALIZING' to 'STOPPING'
2026-04-16 13:18:01,958 INFO  [io.deb.emb.asy.AsyncEmbeddedEngine] (pool-8-thread-1) Engine is stopped. 
2026-04-16 13:18:01,958 INFO  [io.deb.emb.asy.AsyncEmbeddedEngine] (pool-8-thread-1) Engine state has changed from 'STOPPING' to 'STOPPED'
2026-04-16 13:18:01,959 ERROR [io.deb.ser.ConnectorLifecycle] (pool-8-thread-1) Connector completed: success = 'false', message = 'Connector configuration is not valid. The 'database.names' value is invalid: Cannot be empty', erro
at io.debezium.embedded.async.AsyncEmbeddedEngine.validateAndGetConnectorConfig(AsyncEmbeddedEngine.java:776)
at io.debezium.embedded.async.AsyncEmbeddedEngine.initializeConnector(AsyncEmbeddedEngine.java:367)
at io.debezium.embedded.async.AsyncEmbeddedEngine.run(AsyncEmbeddedEngine.java:207)
at io.debezium.server.DebeziumServer.lambda$start$1(DebeziumServer.java:182)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)`

When checking the pipeline's `ConfigMap`, I see the info there:

`debezium.source.database.dbname=test`

We are converting the database property to the database.dbname that is used by the connector. Unfortunately SQL Sever has a special name [database.names](https://debezium.io/documentation/reference/3.5/connectors/sqlserver.html#sqlserver-property-database-names).

The issue is [here](https://github.com/debezium/debezium-platform/blob/3e167b8b0584ed8804ee8e21ee1b121af84ee0f5/debezium-platform-conductor/src/main/java/io/debezium/platform/environment/operator/PipelineMapper.java#L200) , where we just map based on the config name but we should also take in consideration the source.getConnection().getType().

### PR DESCRIPTION
**Pull request by pxcamus**
Fixes debezium/dbz#1828

## Description
Add SQL Server-specific database name configuration support in `PipelineMapper`.

## PR Checklist
- [X] I have read the [contribution guidelines](https://github.com/debezium/debezium/blob/main/CONTRIBUTING.md) and the [governance document](https://github.com/debezium/governance/blob/main/GOVERNANCE.md) on PR expectations.
- [X] Minimal changes to code not directly related to your change (e.g. no unnecessary formatting changes or refactoring to existing code)
- [X] One feature/change per PR unless tightly coupled
- [X] Do a rebase on upstream `main`

### CODE REVIEW

**Comment by pxcamus** [comment]
@mfvitale what do you think of this approach? I will add tests if it is ok. Thanks!

File: debezium-platform-conductor/src/main/java/io/debezium/platform/environment/database/DatabaseConnectionConfiguration.java [hunk 1]
```diff
@@ -26,6 +26,7 @@ public class DatabaseConnectionConfiguration {
 
     public static final String DEBEZIUM_DATABASE_USERNAME_CONFIG = "user";
     public static final String DEBEZIUM_DATABASE_NAME_CONFIG = "dbname";
+    public static final String DEBEZIUM_SQLSERVER_DATABASE_NAME_CONFIG = "dbnames";
```
Comment (mfvitale) [inline debezium-platform-conductor/src/main/java/io/debezium/platform/environment/database/DatabaseConnectionConfiguration.java]: It must be [names](https://debezium.io/documentation/reference/3.5/connectors/sqlserver.html#sqlserver-property-database-names)

**Review by mfvitale — CHANGES_REQUESTED** [review]

**Comment by mfvitale** [comment]
@pxcamus The approach looks good. I just left a comment to address.

**Comment by pxcamus** [comment]
@mfvitale  I tested the code in the Stage UI and it is now working with SQL server FYI.

File: debezium-platform-conductor/src/test/java/io/debezium/platform/environment/operator/PipelineMapperTest.java [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+    @Test
+    public void testMapper_ShouldUseNamesForSqlServer() {
+        var pipeline = mockPipelineWithSource(ConnectionEntity.Type.SQLSERVER, Map.of(
+                DATABASE, "customers",
+                USERNAME, "sa"));
+
+        var result = pipelineMapper.map(pipeline);
+
+        assertThat(result.getSpec().getSource().getConfig().getProps())
+                .containsEntry(DATABASE_CONNECTION_CONFIGURATION_PREFIX + DEBEZIUM_SQLSERVER_DATABASE_NAME_CONFIG, "customers")
```
Comment (mfvitale) [inline debezium-platform-conductor/src/test/java/io/debezium/platform/environment/operator/PipelineMapperTest.java]: Just a nitpick comment. I'd prefer to have the `key` explicit and not use the constant. 

The reason is that in this way if something on the code side changes around the constants the test fails and you are forced to thing if the change can break also some consumer of this. 
Think it as a contract.

**Comment by mfvitale** [comment]
@pxcamus thanks a lot. It LGMT I just left a minor comment, once addressed this can be merged.

File: debezium-platform-conductor/src/test/java/io/debezium/platform/environment/operator/PipelineMapperTest.java (hunk 2 above)
Comment (pxcamus) [reply debezium-platform-conductor/src/test/java/io/debezium/platform/environment/operator/PipelineMapperTest.java]: of course 🤦‍♂️  sorry about that!

**Review by mfvitale — APPROVED** [review]

**Comment by mfvitale** [comment]
Hi @pxcamus It LGTM. I'll merge once the current release process is done.
